// Ported directly from stitch_social_preview_pro/code.html's inline
// tailwind.config + DESIGN.md tokens — the theme is already fully specified
// there, this just makes it a real project config.
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#cbc3d7",
        "inverse-on-surface": "#313030",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-container": "#3f2300",
        "secondary-container": "#3131c0",
        "on-primary-container": "#340080",
        "surface-container-low": "#1c1b1b",
        tertiary: "#ffb869",
        "on-secondary-container": "#b0b2ff",
        secondary: "#c0c1ff",
        "on-primary-fixed-variant": "#5516be",
        "secondary-fixed-dim": "#c0c1ff",
        "primary-fixed-dim": "#d0bcff",
        background: "#131313",
        surface: "#131313",
        "surface-tint": "#d0bcff",
        "secondary-fixed": "#e1e0ff",
        "tertiary-container": "#ca801e",
        "on-error": "#690005",
        primary: "#d0bcff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        error: "#ffb4ab",
        "tertiary-fixed": "#ffdcbb",
        "outline-variant": "#494454",
        "on-tertiary-fixed-variant": "#673d00",
        outline: "#958ea0",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#07006c",
        "surface-container": "#201f1f",
        "surface-container-highest": "#353534",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb869",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#482900",
        "on-primary": "#3c0091",
        "on-primary-fixed": "#23005c",
        "on-background": "#e5e2e1",
        "on-secondary": "#1000a9",
        "inverse-primary": "#6d3bd7",
        "primary-container": "#a078ff",
        "on-tertiary-fixed": "#2c1700",
        "primary-fixed": "#e9ddff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        margin: "32px",
        "container-max": "1280px",
        unit: "4px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg": ["Geist"],
        "body-sm": ["Geist"],
        "display-lg": ["Geist"],
        "label-xs": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "code-base": ["JetBrains Mono"],
        "body-base": ["Geist"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-xs": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "code-base": ["14px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        breathe: {
          "0%, 100%": { opacity: "0.3", transform: "scale(1) translateX(-50%)" },
          "50%": { opacity: "0.5", transform: "scale(1.05) translateX(-48%)" },
        },
        "pop-in": {
          "0%": { opacity: "0", transform: "scale(0.8)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in-up-delay-1": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.1s forwards",
        "fade-in-up-delay-2": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.2s forwards",
        "fade-in-up-delay-3": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) 0.3s forwards",
        breathe: "breathe 8s ease-in-out infinite",
        "pop-in": "pop-in 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards",
        shimmer: "shimmer 3s linear infinite",
      },
    },
  },
  plugins: [],
};
